name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: |
        docker build -t milly-project:latest .

    - name: Deploy and Restart Service
      run: |
        cd /home/ubuntu/prod/milly
        docker compose up -d
